# Generated by Django 3.2.25 on 2024-11-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20241126_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='pharmacy',
        ),
    ]
